# Generated by Django 4.0.5 on 2022-11-05 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DocSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('availability', models.BooleanField()),
                ('gender', models.CharField(max_length=10)),
                ('day_of_week', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('end_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='doctor_search.availabletime')),
                ('start_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='doctor_search.availabletime')),
            ],
        ),
    ]
