# Generated by Django 4.0.5 on 2022-11-05 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='docsearch',
            options={'verbose_name_plural': 'Doctor Availability'},
        ),
        migrations.AlterField(
            model_name='docsearch',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='doctor_search.speciality'),
        ),
    ]
