# Generated by Django 4.0.5 on 2022-11-05 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search', '0006_dayofweek_doctorgender_alter_speciality_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='docsearch',
            name='availability',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='doctor_search.availability'),
            preserve_default=False,
        ),
    ]
