# Generated by Django 4.0.5 on 2022-11-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search', '0007_availability_docsearch_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docsearch',
            name='day_of_week',
        ),
    ]
