# Generated by Django 4.0.5 on 2022-11-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search', '0009_docsearch_day_of_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'ordering': ['speciality'], 'verbose_name_plural': 'Speciality'},
        ),
        migrations.RemoveField(
            model_name='docsearch',
            name='availability',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
