# Generated by Django 4.0.5 on 2022-11-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search', '0010_alter_speciality_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsearch',
            name='availability',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
