# Generated by Django 4.0.5 on 2022-11-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search', '0011_docsearch_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofweek',
            name='day_of_week',
            field=models.CharField(max_length=100),
        ),
    ]
