# Generated by Django 4.0.5 on 2022-11-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search', '0012_alter_dayofweek_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofweek',
            name='day_of_week',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='doctorgender',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
