# Generated by Django 4.0.5 on 2022-11-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search', '0013_alter_dayofweek_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayofweek',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='docsearch',
            options={'ordering': ['name'], 'verbose_name_plural': 'Doctor Availability'},
        ),
    ]
