# Generated by Django 4.0.5 on 2022-11-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search', '0014_alter_dayofweek_options_alter_docsearch_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docsearch',
            name='gender',
        ),
        migrations.DeleteModel(
            name='DoctorGender',
        ),
    ]
