# Generated by Django 4.0.5 on 2022-11-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_pat', '0007_rename_patientgender_gender'),
        ('doctor_search', '0015_remove_docsearch_gender_delete_doctorgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsearch',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='register_pat.gender'),
            preserve_default=False,
        ),
    ]
