# Generated by Django 4.0.5 on 2022-11-03 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('medicond', models.TextField()),
                ('dosage', models.IntegerField()),
                ('perday', models.IntegerField()),
                ('mobile', models.CharField(max_length=15)),
                ('appoint_date', models.DateTimeField()),
                ('medicine_rec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='medicine.medicinerecord')),
                ('medicine_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='register_pat.medicinetime')),
            ],
        ),
    ]
