# Generated by Django 4.0.5 on 2022-11-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_pat', '0002_remove_patientrec_medicine_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrec',
            name='perday',
        ),
    ]
