# Generated by Django 4.0.5 on 2022-11-05 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_medicinerecord_options'),
        ('register_pat', '0003_remove_patientrec_perday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrec',
            name='medicine_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine.medicinerecord'),
        ),
    ]
