# Generated by Django 4.0.5 on 2022-11-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_pat', '0006_patientrec_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientGender',
            new_name='Gender',
        ),
    ]
